############################################################
# Dockerfile to build CentOS base image
# Based on CentOS
############################################################
FROM centos
MAINTAINER Jeremy Thorson

RUN yum update -y && yum upgrade -y