#!/usr/bin/env php

<?php

require_once __DIR__ . '/vendor/autoload.php';

$app = new Silex\Application();

// Parsing Environment Variables here
$env = get_defined_vars();
$env = preg_grep_keys('/DRUPALCI/', $env['_SERVER']);

$console = require __DIR__ . '/scripts/src/drupalci.php';
$console->run();
