#!/usr/bin/env php
<?php
/**
 * @file
 * Drupal CI's console.
 */

$loader = require_once __DIR__ . '/vendor/autoload.php';

use DrupalCI\Console\DrupalCIConsoleApp;

$app = new DrupalCIConsoleApp('DrupalCI - CommandLine', '0.1');
$app->run();
