############################################################
# Dockerfile to add httpd to CentOS base image
# Based on jthorson/centos-base
############################################################
FROM jthorson/centos-base
MAINTAINER Jeremy Thorson

RUN yum install httpd -y && chkconfig httpd on