############################################################
# Dockerfile to add postgres to centos-httpd image
# Based on jthorson/centos-httpd
############################################################
FROM jthorson/centos-httpd
MAINTAINER Jeremy Thorson

RUN yum install -y postgresql-server
